// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2aSh1lEFHqS7oBiACpaKQyhl4QLOZTU',
    appId: '1:182728330349:android:8c649f04f2d5a0cf42c364',
    messagingSenderId: '182728330349',
    projectId: 'shop-joao',
    databaseURL: 'https://shop-joao-default-rtdb.firebaseio.com',
    storageBucket: 'shop-joao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiM5agoxQyJQmHoJ4B0l-qEiBIqi2yXA',
    appId: '1:182728330349:ios:bbc894b01706783f42c364',
    messagingSenderId: '182728330349',
    projectId: 'shop-joao',
    databaseURL: 'https://shop-joao-default-rtdb.firebaseio.com',
    storageBucket: 'shop-joao.appspot.com',
    iosClientId: '182728330349-qn2lnlinmqdkp1fohqd8r8jdnub859lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );
}
